apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: strapi-staging
bases:
  - ./configmap.yaml
  - ./kservice.yaml
images:
  - name: devlaunchers/cms-api
    newName: devlaunchers/cms-api
    newTag: e118911-202203251507 # {"$imagepolicy": "strapi:strapi:tag"}
